baseURL = "https://renebidart.com/"
languageCode = "en-us"
title = "Rene Bidart"

[params]
  description = "PhD student at University of Waterloo, focused on using AI to improve healthcare"
  custom_css = ["/css/style.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreFiles = [
  "old_blogs_ignored/*",
  "README.md"
]
